#!/bin/sh

# hr
#   Start up HoverRace in testing mode.

cd `dirname "$0"`

echo '==> Updating resources...'
( cd share ; make ) || exit 1

echo '==> Updating locales...'
( cd po ; make update-gmo ) || exit 1
build/mklocale.sh po/*.gmo || exit 1

echo '==> Launching HoverRace!'
client/Game2/hoverrace -D --media-path share "$@"

