# Copyright (c) 2012-2015 Sebastien Rombauts (sebastien.rombauts@gmail.com)

# build format
version: "{build}"

# scripts that run after cloning repository
# NOTE : not updating submodule as cloning googletest does not work on AppVeyor
install:
# - git submodule update --init googletest

# configurations to add to build matrix
configuration:
  - Debug
  - Release
 
# scripts to run before build
# NOTE : no unit tests as cloning googletest does not work on AppVeyor
before_build:
  - mkdir build
  - cd build
  - cmake -DSQLITECPP_BUILD_EXAMPLES=ON -DSQLITECPP_BUILD_TESTS=OFF -DSQLITECPP_RUN_CPPCHECK=OFF -DSQLITECPP_RUN_DOXYGEN=OFF ..

# build examples, and run tests (ie make & make test)
build_script:
  - cmake --build .
# - ctest --output-on-failure
