//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Game2.rc
//
#define IDC_ADD                         3
#define IDC_DEFAULT                     3
#define IDC_JOIN                        4
#define IDI_HOVER_ICON                  101
#define IDD_TCP_SERVER                  101
#define IDD_SERVER_PORT                 102
#define IDR_ACCELERATOR                 103
#define IDD_SERVER_ADDR                 103
#define IDD_TCP_CLIENT                  104
#define IDD_NET_PROGRESS                105
#define IDD_DISPLAY_INTENSITY           107
#define IDD_TRACK_SELECT                108
#define IDD_CONTROL                     110
#define IDD_BAD_MODE3                   111
#define IDD_ABOUT                       114
#define IDD_INTERNET_PARAMS             125
#define IDD_SET_MESSAGE                 129
#define IDD_BAD_MODE1                   130
#define IDD_BAD_MODE4                   132
#define IDD_WAIT_ALL                    142
#define IDI_WARNING2                    143
#define IDD_CHAT_MESSAGES               143
#define IDD_INTERNET_MEETING_PUB        150
#define IDD_LADDER_SUBMIT               152
#define IDD_LADDER_RES_3                153
#define IDD_FIRST_CHOICE                154
#define IDD_LADDER_SUBMIT_QUIT          156
#define IDD_LADDER_RETRY                157
#define IDD_LADDER_RES_2                158
#define IDD_LADDER_RES_1                159
#define IDD_LADDER_SUBMIT_PROCESS       160
#define IDD_MISC                        161
#define IDD_DOWNLOAD_PROGRESS           163
#define IDD_WARN_ALONE                  166
#define IDD_PRESS_ANY_KEY               167
#define IDD_NETWORK                     168
#define IDD_PERFORMING_TASK             170
#define IDB_ABOUT                       172
#define IDD_MULTIPLAYER_PREFS           173
#define IDC_GAMMA_SLIDER                1001
#define IDC_CONTRAST_SLIDER             1002
#define IDC_SERVER_PORT                 1002
#define IDC_BRIGHTNESS_SLIDER           1003
#define IDC_SERVER_ADDR                 1003
#define IDC_PLAYER_NAME                 1004
#define IDC_SFX_VOLUME_SLIDER           1004
#define IDC_GAME_NAME                   1005
#define IDC_UPDATE_SERVER_ADDR          1005
#define IDC_LIST                        1007
#define IDC_DESCRIPTION                 1008
#define IDC_MOTOR_ON1                   1011
#define IDC_TEXT                        1011
#define IDC_RIGHT1                      1012
#define IDC_FULL_MENU_MODE              1012
#define IDC_LEFT1                       1014
#define IDC_FIRE1                       1015
#define IDC_SELWEAPON1                  1016
#define IDC_MOTOR_ON2                   1018
#define IDC_RIGHT2                      1019
#define IDC_LEFT2                       1020
#define IDC_CHAT_OUT                    1020
#define IDC_FIRE2                       1021
#define IDC_CHAT_IN                     1022
#define IDC_SELWEAPON2                  1022
#define IDC_JUMP1                       1024
#define IDC_JUMP2                       1025
#define IDC_GAME_LIST                   1026
#define IDC_RIGHT3                      1026
#define IDC_USER_LIST                   1027
#define IDC_LEFT3                       1027
#define IDC_PLAYER_LIST                 1029
#define IDC_JUMP3                       1029
#define IDC_AVAIL_MESSAGE               1030
#define IDC_FIRE3                       1030
#define IDC_NB_LAP_SPIN                 1031
#define IDC_TRACK_NAME                  1031
#define IDC_SELWEAPON3                  1031
#define IDC_NB_LAP                      1032
#define IDC_MOTOR_ON3                   1032
#define IDC_ALIAS                       1033
#define IDC_RIGHT4                      1033
#define IDC_MESSAGE                     1034
#define IDC_LEFT4                       1034
#define IDC_TIMER_CHECK                 1035
#define IDC_HOUR                        1036
#define IDC_JUMP4                       1036
#define IDC_HOUR_SPIN                   1037
#define IDC_FIRE4                       1037
#define IDC_MINUTE                      1038
#define IDC_SELWEAPON4                  1038
#define IDC_MINUTE_SPIN                 1039
#define IDC_CHAT1                       1039
#define IDC_MOTOR_ON4                   1039
#define IDC_CHAT2                       1040
#define IDC_CHAT3                       1041
#define IDC_CHAT4                       1042
#define IDC_CHAT5                       1043
#define IDC_CHAT6                       1044
#define IDC_CHAT7                       1045
#define IDC_WEAPONS                     1057
#define IDC_ROOMLIST                    1059
#define IDC_PUB                         1062
#define IDC_PASSWORD                    1065
#define ID_BTN1                         1068
#define ID_BTN2                         1069
#define IDC_COMMENT                     1070
#define ID_BTN3                         1070
#define IDC_LOOKBACK1                   1076
#define IDC_INTRO_MOVIE                 1076
#define IDC_LOOKBACK2                   1077
#define IDC_SHOW_INTERNET               1077
#define IDC_LOOKBACK3                   1078
#define IDC_LOOKBACK4                   1079
#define IDC_NATIVE_BPP_FULLSCREEN       1079
#define IDC_MAINSERVER                  1081
#define IDC_BRIGHTNESS_TXT              1081
#define IDC_ABOUT_TXT                   1081
#define IDC_CONTRAST_TXT                1082
#define IDC_UPDATESERVER                1082
#define IDC_SFX_VOLUME_TXT              1083
#define IDC_STATE                       1083
#define IDC_GAMMA_TXT                   1084
#define IDC_DLPROGRESS                  1085
#define IDC_UDP_RECV_PORT               1087
#define IDC_TCP_RECV_PORT               1088
#define IDC_TCP_SERV_PORT               1089
#define IDC_VER_TXT                     1090
#define IDC_TRACKS_LBL                  1095
#define IDC_DESC_LBL                    1096
#define IDC_LAPS_LBL                    1097
#define IDC_WEAPONS_CHK                 1099
#define IDC_GAMMA                       1100
#define IDC_MINES_CHK                   1100
#define IDC_CONTRAST                    1101
#define IDC_CANS_CHK                    1101
#define IDC_BRIGHTNESS                  1102
#define IDC_BASIC_CHK                   1102
#define IDC_VOLUME                      1103
#define IDC_FS_RES                      1104
#define IDC_BI_CHK                      1104
#define IDC_PLAYER1                     1105
#define IDC_CX_CHK                      1105
#define IDC_PLAYER2                     1106
#define IDC_EON_CHK                     1106
#define IDC_PLAYER3                     1107
#define IDC_PLAYER4                     1108
#define IDC_MOTOR_ON                    1109
#define IDC_TURN_RIGHT                  1110
#define IDC_TURN_LEFT                   1111
#define IDC_BRAKE                       1112
#define IDC_JUMP                        1113
#define IDC_FIRE_WEAPON                 1114
#define IDC_SELECT_WEAPON               1115
#define IDC_LOOK_BACK                   1116
#define IDC_TCP_SERV_PORT_C             1117
#define IDC_TCP_RECV_PORT_C             1118
#define IDC_UDP_RECV_PORT_C             1119
#define IDC_CLICK_OK                    1120
#define IDC_MAKE_SURE                   1121
#define IDC_YOUR_ALIAS                  1122
#define IDC_ROOM_C                      1123
#define IDC_GAME_LIST_C                 1124
#define IDC_GAME_DETAILS_C              1125
#define IDC_TRACK_NAME_C                1126
#define IDC_LAPS_C                      1127
#define IDC_AVAILABILITY_C              1128
#define IDC_PLAYERS_LIST_C              1129
#define IDC_USERS_LIST_C                1130
#define IDC_CHAT_SECTION_C              1131
#define IDC_WEAPONS_C                   1132
#define IDC_AUDIO_GROUP                 1233
#define IDC_VIDEO_GROUP                 1234
#define IDC_FULLSCREEN_GROUP            1235
#define IDC_MONITOR                     1236
#define IDC_RES                         1238
#define IDC_MONITOR_LBL                 1239
#define IDC_DLITEM                      1333
#define IDC_CRAFTS_BOX                  1336
#define IDC_OPTIONS_BOX                 1337
#define IDC_ASK_AGAIN                   1338
#define IDC_TEXT_WARNING                1339
#define IDC_WARN_TEXT                   1340
#define IDC_DISABLE                     1344
#define IDC_PRESS_ANY_KEY               1345
#define IDC_BRAKE1                      1346
#define IDC_IMR_GROUP                   1346
#define IDC_BRAKE2                      1347
#define IDC_CONNECTION_GROUP            1347
#define IDC_BRAKE3                      1348
#define IDC_BRAKE4                      1349
#define IDC_LOG_CHATS_TXT               1349
#define IDC_LOG_CHATS_BROWSE            1350
#define IDC_LOG_CHATS                   1351
#define IDC_AUTO_CHECK                  1352
#define IDC_SERVER_RESET_DEFAULT        1353
#define IDC_CONNECTION_RESET_DEFAULT    1354
#define IDC_OPEN_FOLDER                 1355
#define IDC_AUDIO_STATUS                1356
#define IDC_UPDATE_SERVER_RESET_DEFAULT 1356
#define IDC_MSG_LBL                     1359
#define IDC_CHECK_URL                   1360
#define IDC_ITEM_NAME                   1361
#define IDC_CHECK_UPDATES               1361
#define IDC_BADMODE_FULLSCREEN_LBL      1363
#define IDC_MAP_SELECT                  1364
#define IDC_CHANGE_BINDING              1367
#define IDC_CONTROL_BINDING             1369
#define IDC_IMR_CLIENT_GROUP            1371
#define IDC_MESSAGE_RECEIVED_SOUND      1372
#define IDC_MESSAGE_RECEIVED_SOUND_ONLY_BG 1373
#define ID_VIEW_3DACTION                32775
#define ID_SETTING_WINDOW               32784
#define ID_GAME_PAUSE                   32788
#define ID_VIEW_DEBUG                   40001
#define ID_VIEW_COCKPIT                 40002
#define ID_GAME_NETWORK_INTERNET        40008
#define ID_VIEW_PLAYERSLIST             40009
#define ID_VIEW_MOREMESSAGES            40010
#define ID_SETTING_REFRESHCOLORS        40013
#define ID_SETTING_FULLSCREEN           40046
#define ID_GAME_EXIT                    40049
#define ID_HELP_ABOUT                   40050
#define IDS_MODE_SWITCH_TRY             40080
#define IDS_CANT_SWITCH_MODE            40081
#define IDS_BAD_MODE                    40082
#define IDS_COMM_ERROR                  40113
#define IDS_CANT_ADDUSER                40114
#define IDS_NOMORE_USER                 40116
#define IDS_CANT_REFRESH                40120
#define IDS_NOL                         40121
#define IDS_CANT_ADD_CHAT               40122
#define IDS_CANT_ADD_GAME               40123
#define IDS_NOMORE_ENTRY                40124
#define IDS_CANT_JOIN                   40125
#define IDS_GAME_NA                     40126
#define IDS_GAME_FULL                   40127
#define IDS_CANT_DEL_GAME               40128
#define IDS_NOT_OWNER                   40129
#define IDS_CANT_LEAVE_GAME             40130
#define IDS_MUST_JOIN                   40131
#define IDS_CANT_DEL_USER               40132
#define IDS_CANT_START_GAME             40133
#define IDS_CANT_ADD_MESSAGE            40134
#define IDS_NOT_AUTH                    40135
#define IDS_UNKNOWN_ERROR               40136
#define IDS_ENTER_ALIAS                 40139
#define IDS_SELECT_ROOM                 40140
#define IDS_WARN_TO                     40141
#define IDS_LOC_MSERVER                 40142
#define IDS_CANT_FIND_SERVER            40143
#define IDS_TO                          40144
#define IDS_SERVER_ERROR                40145
#define IDS_CANT_CREATE_SOCK            40147
#define IDS_TCP_SERVER                  40148
#define IDS_CANT_USE_PORT               40149
#define IDS_PORT_RANGE                  40150
#define IDS_CONNECTING_SERV             40151
#define IDS_GET_GAMEINFO                40152
#define IDS_TCP_CLIENT                  40153
#define IDS_CANT_CONNECT                40154
#define IDS_PLAYER                      40155
#define IDS_LAG                         40156
#define IDS_STATUS                      40157
#define IDS_LOCAL                       40158
#define IDS_CONNECTED                   40159
#define IDS_REG_BEST_LAP                40160
#define IDS_DISCONNECTED                40161
#define IDS_COMPUTING                   40162
#define IDS_CONNECTING                  40163
#define IDS_WAITING_ACK                 40164
#define IDS_NO_NET_CONNECT              40165
#define IDS_DUAL_REG_KEY                40166
#define IDS_F2_TORETURN                 40167
#define IDS_HAS_LEFT                    40168
#define IDS_ALONE_F2                    40169
#define IDS_ALONE                       40170
#define IDS_RANK_TITLE                  40176
#define IDS_FLAP_STR                    40177
#define IDS_CHART_FINISH                40178
#define IDS_CHART                       40179
#define IDS_COUNTDOWN                   40180
#define IDS_FINISH                      40181
#define IDS_FINISH_SINGLE               40182
#define IDS_BEST_LAP                    40183
#define IDS_HEADER                      40184
#define IDS_LAST_LAP                    40185
#define IDS_CUR_LAP                     40186
#define IDS_HIT_TITLE                   40187
#define IDS_HIT_CHART                   40188
#define IDS_JOY1BTN5                    40192
#define IDS_JOY1BTN6                    40193
#define IDS_JOY1BTN7                    40194
#define IDS_JOY1BTN8                    40195
#define IDS_JOY2BTN5                    40196
#define IDS_JOY2BTN6                    40197
#define IDS_JOY2BTN7                    40198
#define IDS_JOY2BTN8                    40199
#define IDS_JOY3BTN1                    40200
#define IDS_JOY3BTN2                    40201
#define IDS_JOY3BTN3                    40202
#define IDS_JOY3BTN4                    40203
#define IDS_JOY3BTN5                    40204
#define IDS_JOY3BTN6                    40205
#define IDS_JOY3BTN7                    40206
#define IDS_JOY3BTN8                    40207
#define IDS_JOY3TOP                     40208
#define IDS_JOY3DOWN                    40209
#define IDS_JOY3RIGHT                   40210
#define IDS_JOY3LEFT                    40211
#define IDS_JOY4BTN1                    40212
#define IDS_JOY4BTN2                    40213
#define IDS_JOY4BTN3                    40214
#define IDS_JOY4BTN4                    40215
#define IDS_JOY4BTN5                    40216
#define IDS_JOY4BTN6                    40217
#define IDS_JOY4BTN7                    40218
#define IDS_JOY4BTN8                    40219
#define IDS_JOY4TOP                     40220
#define IDS_JOY4DOWN                    40221
#define IDS_JOY4LEFT                    40222
#define IDS_JOY4RIGHT                   40223
#define IDS_CANT_USE_UDP_PORT           40225
#define IDS_GAME_CANCELLED              40226
#define IDS_CONN_REFUSED1               40228
#define IDS_CONN_REFUSED2               40229
#define IDS_CONN_TIMEOUT1               40230
#define IDS_CONN_TIMEOUT2               40231
#define IDS_SAMEADDRPORT1               40232
#define IDS_SAMEADDRPORT2               40233
#define IDS_CONN_ERROR                  40234
#define IDS_INVALID_RESOLUTION          40240
#define IDS_TEST_RESOLUTION             40241
#define IDS_SET_RESOLUTION              40242
#define IDS_INVALID_RESOLUTION2         40243
#define ID_GAME_NEW                     0xE100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         40052
#define _APS_NEXT_CONTROL_VALUE         1374
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
