#pragma once
#define HR_APP_VERSION @HR_APP_VERSION_MAJOR@,@HR_APP_VERSION_MINOR@,@HR_APP_VERSION_PATCH@,@HR_APP_VERSION_BUILD@
#cmakedefine01 HR_APP_PRERELEASE
#define HR_APP_VERSION_PRERELEASE (static_cast<bool>(HR_APP_PRERELEASE))
